#!/bin/bash
#SBATCH --partition=gpu 
#SBATCH --gpus=1 
#SBATCH --mem=16gb 
#SBATCH --constraint=a100 
#SBATCH --time=12:00:00
#SBATCH --job-name=ABCDNet
#SBATCH --account avery 
#SBATCH --qos avery
echo "job init: $(date)"

source setup_hpg.sh
python python/ingress.py $1
python python/train.py $1 --log_interval=10
python python/infer.py $1 --epoch=100
python scripts/plot.py $1 --epoch=100

echo "job done: $(date)"
